### ISSUE TITLE
try installing and fix

### ISSUE THREAD

**Issue by kbumsik** [Wolfie-Home/webserver2#1]
I and @joannyang will install this project. We will fix or change some code to make this more general.

**Comment by cjackie** [comment]
Nice, need any help, let me know. 👍

**Comment by kbumsik** [comment]
Hi @cjackie, I made the server working now!
I show a screen asking username and password.
I have two questions:
1. Looks like I I need to add a user manually through SQL. But I am not sure what data should be in `house_info` column. By the way, please verify [table I have created](https://github.com/Wolfie-Home/Documents/blob/bumsik/Design%20Document/Design_Document.md#51-mysql) meets your intention.
2. Please tell me how far the webpage is implemented. What the webpage supposed to do?

Thank you :)

**Comment by kbumsik** [comment]
Oh, that's okay. I got it. Thanks.

**Comment by cjackie** [comment]
@kbumsik 
Great work! 
1. house_info has [this schema](https://github.com/Wolfie-Home/Documents/blob/master/Design%20Document/schema/house_info.json). But now I don't think it is a good design. I wanted to express the logic that house contains many things, which I later found out had been study a lot in database. A better design could be using [relationship](http://coderscampus.com/database-relationships-one-to-many/) to construct such logic
2. Not sure what do you mean, could you elaborate?

**Comment by cjackie** [comment]
Possible answer:
2. two pages need to be implemented: 
- /house page, which will display status about devices that user has in the house.
- /message page, which will send mqtt commands to devices.
  all UI desgin is not mentioned in the design document, we should layout the design before implementing these two pages.

**Comment by cjackie** [comment]
@yiochen 
If you have time, could you do a design for us? If you have limited time, you could just draw a layout on a paper. 😄

**Comment by kbumsik** [comment]
@cjackie Thanks for a quick reply. Your answer 2 is exactly I needed. My server is currently working as you described. Your source code looks very clear to me, thanks. (By the way, @joannyang also successfully installed the server as well. She did it with me)

**Comment by cjackie** [comment]
Nice, I will take a look at your branch tonight, and possibly merge it to the master branch.

**Comment by kbumsik** [comment]
I had make PR #4 for you. feel free to comment on it :)

**Comment by kbumsik** [comment]
The issue resolved. Closed.
