### ISSUE TITLE
Switching to Stored procedures from ad-hoc queries.

### ISSUE THREAD

**Issue by kbumsik** [Wolfie-Home/webserver2#2]
Currently, the project uses ad-hoc queries to get data from the DB.
I will refactor them to use Stored procedures. Stored Procedures has [a lot of benefits](http://stackoverflow.com/a/209094/4661625) over ad hoc queries.

**Comment by cjackie** [comment]
Yep. Ad hoc is very bad idea. 
We should use [this](https://docs.djangoproject.com/en/1.10/topics/db/models/) since we are using Django. I believe this is [ORM](http://tutorial.djangogirls.org/en/django_orm/).

**Comment by kbumsik** [comment]
As far as I know there are largely two options to implement `Models` in MVC pattern.
1. Using ORM that is supported by application framework.
2. Using SQL and Write Model classes that fetch data using Stored Procedures.

Stored procedures is single/multiple SQL queries stored in the DB. We can call them from DB like function call, not writing SQL queries as strings. We can see [a simple example here.](http://www.chrisumbel.com/article/django_python_stored_procedures.aspx)
I personally prefer the second option because what I am doing in internship is refactoring web applications on .NET MVC framework and I usually do a lot of SQLs and data table designs. So I can work with you much when we use SQL. We don't need to learn their ORM APIs. SQL can make our python code simpler.
What do you think? It is just my opinion.

**Comment by cjackie** [comment]
I checked the example. Stored Procedures is much more generic and flexible. Awesome! Since you know it better, you should just use it. 😆 
ORM in django was meant to be easy and simple(limited in functionality), but the learning curve is little bit high. Since Stored Procedures is easier for you, you should definitely stick with it. With its flexibility, it will be useful when the db gets complicated and needs customization.

**Comment by kbumsik** [comment]
@cjackie Great. Thanks. Django ORM looks a little bit confusing to be honest :stuck_out_tongue: . I will upload a simple table ER diagram and basic SQLs, observing your initial design intention described in JSON by Saturday night, including discussed in #1 and #3 . It will help you design it later.

**Comment by cjackie** [comment]
In case you don't know, there is a tool called mysql-workbench for mysql that might be helpful to you, when you do the ER diagram.

**Comment by kbumsik** [comment]
[Basic database design is finally done!](https://github.com/Wolfie-Home/Documents/issues/2) 
I am writing my idea on how to use stored procedure here. 
In many web application, there are some more layers(or class design pattern) beneath `Model` (used in `springMVC` and `.NET MVC framework`).
- `DAO` (Data Access Object): This one accesses directly to Database. In our case, these object call Stored Procedures directly and get return data. Does not do more.
- `Service` : Provides higher abstraction and interface to the application server on top of `DAO`. For example, some data conversions or security stuff added to `DAO`.

So, we have made `Model`. When the `Controller` receives request from a client. `Controller` calls `Services` to get data from server and then fetch to `Model` object. Then send `Model` object to `View`.
`DAO` and `Service` however are often bundled together into one.

I think a strong candidate for our `Service` layer is [Model Manager](https://docs.djangoproject.com/en/1.10/topics/db/managers/) classes. Methods of `Model Manager` may call stored procedures.

If we want to use my SP that's worth a shot.

[another reference](https://djangosnippets.org/snippets/272/)

**Comment by cjackie** [comment]
> I think a strong candidate for our `Service` layer is [Model Manager](https://docs.djangoproject.com/en/1.10/topics/db/managers/) classes. Methods of `Model Manager` may call stored procedures.

Yep, we can extend manager class to utilize your SP. By the way, a nice thing about the manager is that many common db queries is already implemented. And it can interface with different DB. But it is less reflexible and not that good in performance.

Django ORM to DBs is sort of like VFS to filesystems in Linux.

**Comment by kbumsik** [comment]
Eventually, I decided to throw SP away 😮 . Haha. I realized I need more flexible approach than SP. Refer #9 . Closing the issue.
