### ISSUE TITLE
split JSON objects into Tables/Colums

### ISSUE THREAD

**Issue by kbumsik** [Wolfie-Home/webserver2#3]
At the beginning of the project we designed to store JSON objects into DB. After leaning about database I realized that [this is really bad for RDBMS design.](http://stackoverflow.com/questions/15367696/storing-json-in-database-vs-having-a-new-column-for-each-key) Database table design is different from object-oriented design. If we want to use JSON we can use NoSQL such as mongoDB but I am no considering using them now and also [NoSQL is not always better in any kinds of design](http://stackoverflow.com/questions/4160732/nosql-vs-relational-database). We could switch to NoSQL later but let's do a traditional way first.
This regards only how we store data in DB. We don't need to change anything about communication models using JSON at this moment.

**Comment by cjackie** [comment]
Yea, in terms of performance, it is a bad idea.
Take a look at django ORM, it might help.

**Comment by kbumsik** [comment]
Things is discussed here. #2

**Comment by kbumsik** [comment]
I close this issue because it no longer store JSON object in the db.
