### ISSUE TITLE
Integration with DB and major clean up

### ISSUE THREAD

**Issue by cjackie** [Wolfie-Home/webserver2#7]
@Wolfie-Home/admin 

So, Django ORM has been generated and I have cleaned up the code. Please review it at [here](https://github.com/Wolfie-Home/webserver2/tree/integration). If It is okay, I will start merging to master branch.

**Comment by kbumsik** [comment]
Could you make a pull request? Reviewing codes using pull request is better for me.
PR acts like an issue too.

**Comment by kbumsik** [comment]
I close the issue because the corresponding PR is merged.
